python:
<<<<<<< HEAD
  -  2.7.7
install:
  - pip install -r requirements.txt
  - pip install coveralls
after_success:
  - coveralls
    
=======
   -  3.4.3
install:
   - pip install -r requirements.txt
   - pip install coveralls
after_success:
   - coveralls
>>>>>>> development
