language: python

python:
   -  3.4.3
   
install:
   - pip install -r requirements.txt
   - pip install coveralls

script:
   - nosetests -v --with-coverage --cover-package=tests

after_success:
   - coveralls
